### ISSUE TITLE
Adds spaces inside node values

### ISSUE THREAD

**Issue by gitowiec** [chrisbottin/xml-formatter#3]
Pretty printing with xml-formatter changes values of nodes, eg from
```
<node>value</node>
```
to 
```
<node>
   value
</node>
```
what makes the resulting xml non validable with its schema.

Solution could be pretty printing without adding spaces inside values (just around nodes)

**Comment by chrisbottin** [comment]
I think you might need to use the attribute `xml:space="preserve"` inside the `node` element to avoid pretty printing the code inside.

**Comment by mellis481** [comment]
This is the issue I'm having.  I understanding adding the attribute `xml:space="preserve"` resolves the issue, but that attribute is rendered.  Is there any way to format nodes like this that contain content (rather than additional nodes) so they do not span multiple lines?  I was hoping it would be an `options` prop...

**Comment by chrisbottin** [comment]
@mellis481 please see comments in https://github.com/chrisbottin/xml-formatter/issues/5 as it might also meet your needs
