### ISSUE TITLE
When using the "xmlFormatter()" VS code does not able to identify.

### ISSUE THREAD

**Issue by harshitgupta028** [chrisbottin/xml-formatter#68]
Hi There,

```
var xmlFormatter = require("xml-formatter");

console.log(xmlFormatter(.....XML code goes here............));
```

So, xmlFormatter() VS code is not able to recognise it.

Error:

This expression is not callable.
  Type 'typeof import("c:/Users/<username>/Documents/Extension/xquery-formatter/node_modules/xml-formatter/dist/types/index")' has no call signatures.
  
Now, the interesting part is after running the code it is working i.e. I'm getting the formatted code.

**Comment by chrisbottin** [comment]
Hi @harshitg123, can you let me know how you are using `xml-formatter` inside VS code so I can replicate the issue?

**Comment by harshitg123** [comment]
Hello @chrisbottin,

```
const xmlFormatter = require('xml-formatter');

xmlFormatter('<root>' + fetchXqueryData() + '</root>', {
			indentation: ' ',
			lineSeparator: '\n'
		})
```

fetchXqueryData() is a function which is fetching the XQuery. for sample you can use.

```
<xml>
  <person country="USA" name="John"/>
  <person country="USA" name="Jack"/>
  <person country="Germany" name="Johann"/>
 </xml>
```

<img width="1470" alt="Screenshot 2024-01-13 at 12 19 11 AM" src="https://github.com/chrisbottin/xml-formatter/assets/58328462/eefcc4ef-e052-4c05-94f8-b6ea55be87c5">

**Comment by chrisbottin** [comment]
Thanks, I see what you mean now ... literally 😄.

I will take a look and get back to you.

**Comment by chrisbottin** [comment]
@harshitg123 I'm not able to replicate the issue yet, perhaps it's a VS code configuration thing.

Can you share your `jsconfig.json` and any other configs that might be needed (package.json, etc)?

**Comment by harshitg123** [comment]
@chrisbottin 

jsconfig.json file

```
{
	"compilerOptions": {
		"module": "Node16",
		"target": "ES2022",
		"checkJs": true,  /* Typecheck .js files. */
		"lib": [
			"ES2022"
		]
	},
	"exclude": [
		"node_modules"
	]
}
```

I guess it is something related to the typescript check, If I make "checkJs" to false the error is gone.

**Comment by chrisbottin** [comment]
@harshitg123 I have made some changes in version `3.6.1` which should fix this problem.

The issue was the TS declaration file was intended for ES module type but you are using CommonJS and making use of the TS declaration file using `jsconfig.json` with `checkJs`.

Now the new TS declaration file should be compatible with both ES and CommonJS module types.

**Comment by harshitg123** [comment]
Thanks @chrisbottin I've installed the new version it's working fine now  👍🏻

**Comment by udavx** [comment]
Hi, @chrisbottin 

I was wondering whether the new `compile:types:post-hook` script
- (a) really works (the extra empty pair of quotes makes my `sed` here somewhat confused),
- (b) really does what is needed, because the resulting `dist/types/index.d.ts` makes `tsc` hiss at me
```
node_modules/xml-formatter/dist/types/index.d.ts:57:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

57 export = formatXml;
   ~~~~~~~~~~~~~~~~~~~
```

I will continue scratching my head and looking for configuration switches, of course, but still.

**Comment by chrisbottin** [comment]
Hi @udavx,

Yes the new `compile:types:post-hook` script works as intended. 

a) The `sed` command is targeted to Mac. 
b) Yes, you're right, it makes the declaration file slightly incorrect as you pointed out but I went for it since it makes it work for commonJS and ES module project setup.

What's your tsconfig.json / project setup? You should not have `tsc` reporting errors from the `node_modules` folder. 

If you share your setup, I can have a look.

**Comment by chrisbottin** [comment]
The changes made previously have been reverted as they caused other issues (https://github.com/chrisbottin/xml-formatter/issues/70)

@udavx, this should sort out your problem.

@harshitg123, we will need to come up with another solution.

Instead of using CommonJS modules, can you use ES modules?

You will need to change the `require` statements to `import` and set `"type": "module"` in your package.json

**Comment by udavx** [comment]
@chrisbottin, thank you for the prompt action (incl. the 3.6.2)

For the record or not, `"exclude"` of my `tsconfig.json` does have an entry for `"node_modules"`.

I tried to create a minimal set to reproduce it, here it is: https://github.com/udavx/demo-for-issue-68-of-xml-formatter-3.6.1

Initially, it's `npx tsc` to reproduce, I will proceed with adding some npm scripts and stuff.

**Comment by harshitg123** [comment]
Hi @chrisbottin,

https://github.com/chrisbottin/xml-formatter/issues/68#issuecomment-1902035156

Sure, Let me check and update it.

**Comment by harshitg123** [comment]
Hi @chrisbottin,

I've used  `type: module` in package.json but by doing this I cannot import my own exported functions in the extension.js file.

<img width="932" alt="image" src="https://github.com/chrisbottin/xml-formatter/assets/58328462/098b8a84-41e8-419d-86da-5a3b886286f7">

**Comment by chrisbottin** [comment]
@harshitg123, try with this jsconfig.json ...

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "checkJs": true
  },
  "exclude": ["node_modules"]
}
```

And you might need to add `.js` at the end of the filenames in the imports.

**Comment by harshitgupta028** [comment]
Hi @chrisbottin, Really sorry for reply was occupied by some urgent work.

It worked for me, Thanks
